### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-parent-pom#3]
right now, when components are deployed to maven central, they are not "auto-released".
that is, one always needs to go to the nexus repository manager and release the component/package.
it gives a better control but maybe in the future, we could change this?

**Comment by khituras** [comment]
Ah right. This should be changed in the future. But perhaps, just to be on the safe side, the next release should happen as before. If everything goes fine we could schedule the change to auto release for JCoRe 2.3?

**Comment by fmatthies** [comment]
Maybe we should refrain from auto-release... it's just a minor inconvenience to release it by hand but adds some more control

**Comment by khituras** [comment]
For now, I'd say we refrain from auto-release for the foreseeable future.
