### ISSUE TITLE
Removal of jcore-version property?

### ISSUE THREAD

**Issue by khituras** [JULIELab/jcore-parent-pom#4]
I think we only use this property to refer dependencies to the current release of JCoRe. But this could also be done using the property project.parent.version which would also release us from updating the property by hand.

**Comment by fmatthies** [comment]
I see!
Let's remove it then :)

**Comment by khituras** [comment]
I actually have begun using it in projects that inherit indirectly from the jcore-parent-pom. Thus, the property is useful and we will keep it.
